jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# Provision Tomcat servers on AWS with Ansible
  - name: provision_aws_ansible_provision_tomcat
    type: runCLI
    steps:
      - IN: provision_aws_ansible_repo
      - IN: provision_aws_ansible_cli
      - IN: provision_aws_ansible_keypair
      - TASK:
        - script: >
            export
            AWS_ACCESS_KEY_ID=$PROVISION_AWS_ANSIBLE_CLI_INTEGRATION_AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY=$PROVISION_AWS_ANSIBLE_CLI_INTEGRATION_AWS_SECRET_ACCESS_KEY
        - script: shippable_replace $PROVISION_AWS_ANSIBLE_REPO_STATE/ansible.cfg
        - script: |
            sudo apt-get install software-properties-common
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt-get update
            sudo apt-get install ansible 
            sudo apt-get install python-boto
        - script: |
            cd $PROVISION_AWS_ANSIBLE_REPO_STATE
            ansible-playbook -v ansible-ec2-tomcat-provision.yml
    flags:
      - provision-aws-ansible

# Terminate Tomcat servers on AWS with Ansible
  - name: provision_aws_ansible_terminate_tomcat
    type: runCLI
    steps:
      - IN: provision_aws_ansible_provision_tomcat
        switch: off
      - IN: provision_aws_ansible_repo
        switch: off
      - IN: provision_aws_ansible_cli
      - IN: provision_aws_ansible_keypair
      - TASK:
        - script: >
            export
            AWS_ACCESS_KEY_ID=$PROVISION_AWS_ANSIBLE_CLI_INTEGRATION_AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY=$PROVISION_AWS_ANSIBLE_CLI_INTEGRATION_AWS_SECRET_ACCESS_KEY
        - script: shippable_replace $PROVISION_AWS_ANSIBLE_REPO_STATE/ansible.cfg
        - script: |
            sudo apt-get install software-properties-common
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt-get update
            sudo apt-get install ansible 
            sudo apt-get install python-boto
        - script: |
            cd $PROVISION_AWS_ANSIBLE_REPO_STATE
            ansible-playbook -v ansible-ec2-tomcat-terminate.yml
    flags:
      - provision-aws-ansible

