---
- name: Provision EC2 instances
  local_action:
    module: ec2
    key_name: "{{ ec2_keypair }}"
    group_id: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
    region: "{{ ec2_region }}"
    instance_tags: '{"Name":"{{ec2_tag_Role}}","Role":"{{ec2_tag_Role}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    assign_public_ip: yes
    wait: true
    exact_count: "{{ ec2_count }}"
    count_tag:
      Role: "{{ ec2_tag_Role }}"
    volumes: 
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true
  register: ec2

- add_host: 
    name: "{{ item.public_ip }}" 
    groups: tag_Type_{{ec2_tag_Type}},tag_Environment_{{ec2_tag_Environment}}
    ec2_region: "{{ ec2_region }}" 
    ec2_tag_Name: "{{ ec2_tag_Role }}"
    ec2_tag_Role: "{{ ec2_tag_Role }}"
    ec2_tag_Type: "{{ ec2_tag_Type}}"
    ec2_tag_Environment: "{{ ec2_tag_Environment }}"
    ec2_ip_address: "{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host={{item.public_ip}} port=22 delay=15 timeout=120 state=started
  with_items: "{{ ec2.instances }}"
